version: "3.5"
services: 
  api:
      build: ./api
      volumes:
        - ./api:/api
        - /api/node_modules
      ports:
        - 3000:3000
      depends_on:
        - mongo 
      environment:
        MONGO_HOST: mongo:27017
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27018:27017
    container_name: db
    volumes: 
      - ~/mongo/data:/data/db
    logging:
      driver: none
  mongoku:
    image: huggingface/mongoku
    depends_on:
        - "mongo"
    links:
        - "mongo"
    ports:
        - 3100:3100
    environment:
        MONGOKU_DEFAULT_HOST: mongo